version: "3"
services:
  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=mynews
      - POSTGRES_USER=mynews_user
      - POSTGRES_PASSWORD=mynews_pass
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/posgresql/data
volumes:
  db-data: